# Generated by Django 4.0.4 on 2022-04-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=200)),
                ('chapter', models.IntegerField(max_length=1000)),
                ('video', models.TextField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historywatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.TextField(default='', max_length=100, unique=True)),
                ('movieName', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=200)),
                ('chapter', models.IntegerField(max_length=100)),
                ('totalChapter', models.IntegerField(max_length=100)),
                ('views', models.IntegerField(max_length=1000000)),
                ('description', models.TextField(max_length=1000)),
                ('openingSong', models.TextField(max_length=100)),
                ('closingSong', models.TextField(max_length=100)),
                ('movieLink', models.TextField(default='', max_length=1000)),
                ('picture', models.TextField(default='', max_length=100)),
                ('background', models.TextField(default='', max_length=100)),
                ('type', models.TextField(default='', max_length=100)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.category')),
                ('providerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.provider')),
            ],
        ),
    ]
