# Generated by Django 4.0.4 on 2022-04-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('repassword', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=200, null=True)),
                ('fullname', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, default='', max_length=5, null=True)),
            ],
        ),
    ]
