# Generated by Django 4.0.4 on 2022-04-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Viewer',
        ),
    ]
