# Generated by Django 4.0.4 on 2022-05-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_rename_user_viewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('message', models.TextField(blank=True, default='', max_length=999, null=True)),
                ('movieName', models.CharField(max_length=200)),
            ],
        ),
    ]
